import 'server-only';
import type { Metadata } from 'next';

import { LayoutProps } from '@/types/app';
import { inter, oswald } from '@/ui/fonts';
import '@/styles/main.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps) {
	return (
		<html lang="en" className={`${oswald.variable} ${inter.variable}`}>
			<body className="font-inter">{children}</body>
		</html>
	);
}
