import 'server-only';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { LayoutProps } from '@/types/app';
import '@/styles/main.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps) {
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
